apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
spec:
  replicas: 1  
  selector:    
    name: busybox
  template:    
    metadata:
      labels:  
        name: busybox
    annotations:
        kubernetes.io/hostname=inf164.coe.muc.redhat.com
    spec:
     containers:
     - image: busybox
       command:
        - sleep
        - "36000"
       name: busybox
       volumeMounts:
        - mountPath: /usr/share/busybox
          name: mypvc
     volumes:
       - name: mypvc
         persistentVolumeClaim:
           claimName: gluster-claim
