apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
     requests:
       storage: 10Gi 
     selector:
       matchLabels:
         storage: test
